services:
  # Service 1:
  web:
    build: .
    #command: sh -c "python init_db.py && gunicorn -w 2 --timeout 300 --reload -b 0.0.0.0:5000 app:app"
    command: gunicorn -w 2 --timeout 300 --reload -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis_db  
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:password@db:5432/ai_hr_db
      # Pinecone Keys 
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      # Ollama Connection 
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    depends_on:
      - redis_db
    env_file:
      - .env  

  # Service 2: Redis Database
  redis_db:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_hr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: